import type { Metadata } from "next";
import "./globals.css";
import localFont from "next/font/local";
import { ReduxProvider } from "@/Lib/ReduxProvider";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";


const spartan = localFont({
  src: [
    {
      path: "../../public/fonts/Spartan/LeagueSpartan-Thin.ttf",
      weight: "100",
      style: "normal",
    },
    {
      path: "../../public/fonts/Spartan/LeagueSpartan-ExtraLight.ttf",
      weight: "200",
      style: "normal",
    },
    {
      path: "../../public/fonts/Spartan/LeagueSpartan-Light.ttf",
      weight: "300",
      style: "normal",
    },
    {
      path: "../../public/fonts/Spartan/LeagueSpartan-Regular.ttf",
      weight: "400",
      style: "normal",
    },
    {
      path: "../../public/fonts/Spartan/LeagueSpartan-Medium.ttf",
      weight: "500",
      style: "normal",
    },
    {
      path: "../../public/fonts/Spartan/LeagueSpartan-SemiBold.ttf",
      weight: "600",
      style: "normal",
    },
    {
      path: "../../public/fonts/Spartan/LeagueSpartan-Bold.ttf",
      weight: "700",
      style: "normal",
    },
    {
      path: "../../public/fonts/Spartan/LeagueSpartan-ExtraBold.ttf",
      weight: "800",
      style: "normal",
    },
    {
      path: "../../public/fonts/Spartan/LeagueSpartan-Black.ttf",
      weight: "900",
      style: "normal",
    },
  ],
  variable: "--font-spartan", 
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${spartan.variable} antialiased`}
      >
        <ReduxProvider >
          {children}
        </ReduxProvider>
        <ToastContainer limit={1}/>
      </body>
    </html>
  );
}
